package gram

// var term map[string]int

func init() {
	// term = make(map[string]int)
	// term["and"] = 1
	// term["begin"] = 2
	// term["bool"] = 3
	// term["do"] = 4
	// term["else"] = 5
	// term["end"] = 6
	// term["false"] = 7
	// term["if"] = 8
	// term["integer"] = 9
	// term["not"] = 10
	// term["or"] = 11
	// term["program"] = 12
	// term["real"] = 13
	// term["then"] = 14
	// term["true"] = 15
	// term["var"] = 16
	// term["while"] = 17
	// term["("] = 18
	// term[")"] = 19
	// term["+"] = 20
	// term["-"] = 21
	// term["*"] = 22
	// term["/"] = 23
	// term["."] = 24
	// term[","] = 25
	// term[":"] = 26
	// term[";"] = 27
	// term[":="] = 28
	// term["="] = 29
	// term["<="] = 30
	// term["<"] = 31
	// term["<>"] = 32
	// term[">"] = 33
	// term[">="] = 34
	// term["A"] = 35
	// term["B"] = 36
	// term["C"] = 37
	// term["D"] = 38
	// term["E"] = 39
	// term["F"] = 40
	// term["G"] = 41
	// term["H"] = 42
	// term["I"] = 43
	// term["J"] = 44
	// term["K"] = 45
	// term["L"] = 46
	// term["M"] = 47
	// term["N"] = 48
	// term["O"] = 49
	// term["P"] = 50
	// term["Q"] = 51
	// term["R"] = 52
	// term["S"] = 53
	// term["T"] = 54
	// term["U"] = 55
	// term["V"] = 56
	// term["W"] = 57
	// term["X"] = 58
	// term["Y"] = 59
	// term["Z"] = 60
	// term["a"] = 61
	// term["b"] = 62
	// term["c"] = 63
	// term["d"] = 64
	// term["e"] = 65
	// term["f"] = 66
	// term["g"] = 67
	// term["h"] = 68
	// term["i"] = 69
	// term["j"] = 70
	// term["k"] = 71
	// term["l"] = 72
	// term["m"] = 73
	// term["n"] = 74
	// term["o"] = 75
	// term["p"] = 76
	// term["q"] = 77
	// term["r"] = 78
	// term["s"] = 79
	// term["t"] = 80
	// term["u"] = 81
	// term["v"] = 82
	// term["w"] = 83
	// term["x"] = 84
	// term["y"] = 85
	// term["z"] = 86
	// term["0"] = 87
	// term["1"] = 88
	// term["2"] = 89
	// term["3"] = 90
	// term["4"] = 91
	// term["5"] = 92
	// term["6"] = 93
	// term["7"] = 94
	// term["8"] = 95
	// term["9"] = 96
	// term["#"] = 38
	// term["ε"] = 39
}
